読み間違いの報告機能を実装
actlaboratory/ERE pull request #6
Opened 2023-12-22 12:06 UTC by kitabatake1013

fixed #5

問題がなければ、Issue作成先のリポジトリ情報を正規のものに書き換えてマージします。

2023-12-22 13:05 UTC, yamahubuki requested changes
GUI部分以外は一通り見ました。
GUIは後日コンパイルして入れてみてからレビューします。

2023-12-22 13:05 UTC, yamahubuki commented on addon/globalPlugins/ERE/__init__.py
> +		config.conf["ERE_global"]["accessToken"] = d.GetValue().strip()
簡単な形式チェックと有効性の検証くらいはしてから保存すべきと思います。
桁数や戦闘の文字列での形式チェックと、事故情報取得などの無害なAPI呼び出しによる有効性の確認をしましょう。

2023-12-22 13:05 UTC, yamahubuki commented on addon/globalPlugins/ERE/constants.py
> +GH_ISSUE_LABEL = "sent_from_addon"
第三者のリポジトリのissueに対してlabelの付与ってできたでしょうか。
トリアージ権限ないと無理な気がするので確認しておいてください。

2023-12-22 13:05 UTC, yamahubuki commented on addon/globalPlugins/ERE/ghUtil.py
> +			print("Response from " + result.url + ": " + str(result.status))
NVDA的に、printのままでよいのでしょうか。
ちゃんとログ出力機能を使うべき泣きもします。

2023-12-22 13:05 UTC, yamahubuki commented on addon/globalPlugins/ERE/dialogs/reportMisreadingsDialog.py
> +		# end validation
wordについては英語である、1単語である等のバリデーションは不要でしょうか。

2023-12-26 06:05 UTC, kitabatake1013 commented
修正しました。

labelの付与がどうなるかについては、現状 @yamahubuki さんには何の権限もないリポジトリにIssueを作成するようにしているので、そちらで実行した際にどうなるかをご報告ください。

報告時に英語カナ変換の形式と一致させる必要は、特にないと考えています。
前後関係も含めて、読み方の違和感についてはそのまま報告してほしいと思っているからです。
必要な部分の切り出しや修正はこちらで行います。

2023-12-26 13:32 UTC, yamahubuki requested changes
View以外は確認しました。

2023-12-29 16:21 UTC, yamahubuki reviewed
画面レイアウトに問題がないことを確認しました。

ただし、手元のトークンを使ってリクエストした結果401エラーになった際、ログは残りますがユーザーに何らのエラー通知もなされないようです。
まずは、この点を修正してください。

トークン登録画面でトークン入れた際のエラーです。
ERROR - external:globalPlugins.ERE.ghUtil.GhUtil.isActive (01:09:59.973) - MainThread (9780):
Traceback (most recent call last):
  File "C:\Users\yuki\Documents\soft\For Brind\SCR Reader\NVDA21.2\userConfig\addons\EnglishReadingEnhancer\globalPlugins\ERE\ghUtil.py", line 52, in isActive
    result = self._request("/user")
  File "C:\Users\yuki\Documents\soft\For Brind\SCR Reader\NVDA21.2\userConfig\addons\EnglishReadingEnhancer\globalPlugins\ERE\ghUtil.py", line 28, in _request
    return request.urlopen(r)
  File "urllib\request.pyc", line 222, in urlopen
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 641, in http_response
  File "urllib\request.pyc", line 569, in error
  File "urllib\request.pyc", line 503, in _call_chain
  File "urllib\request.pyc", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

2023-12-29 16:41 UTC, yamahubuki commented
上記エラー、トークンの有効性確認に/user/を使っているのに、トークンにusersの権限がないという理由で生じている気がします。

なので、まずエラーが出ないのを直して、それからusersの権限がなくてもトークンの検証ができるように修正をしてください。

2023-12-30 02:47 UTC, kitabatake1013 commented
トークンの設定時にトレースバックが出るにも関わらず、エラーメッセージが表示されないということですか？
それは変ですね。
Issueの作成権限がどうであれ、動作確認に使っているAPIを使用できなければエラーが表示されるはずなのですが。
後ほど調査します。

2023-12-30 06:26 UTC, kitabatake1013 commented
トークンの有効性確認に使っているAPIは「[認証されているユーザーの情報を取得する](https://docs.github.com/ja/rest/users/users?apiVersion=2022-11-28#get-the-authenticated-user)」というもので、権限がなくても、ステータスコード200で、公開されたプロフィールを返すように読めます。
実際に、個人用アクセス トークンの作成時にどのスコープにもチェックを入れなかった場合でも、`isActive()`はTrueを返しています。

@yamahubuki 以下の手順でデバッグレベルのログを取ってみていただけますか？
個人情報を含むと思うので、ログの内容は非公開の場所で私に送ってください。

1. NVDAメニューの[English Reading Enhancer]→[読み間違いの報告]→[GitHub アクセス トークンの設定]を開き、設定されたトークンを削除（この後の手順を考えるならば切り取り）して、OKボタンを押す。
2. NVDA+Qで表示される終了オプションで[デバッグログを有効化して再起動]を選んでOKボタンを押す。
3. NVDAメニューの[English Reading Enhancer]→[読み間違いの報告]→[GitHub アクセス トークンの設定]を開き、先ほど切り取ったトークンを入力してOKボタンを押す。→ここでエラーメッセージが表示されないのは期待通りの動作です。
4. NVDAメニューの[English Reading Enhancer]→[読み間違いの報告]→[読み間違いの報告]を開き、何らかの内容を入力してOKボタンを押す。→適切な権限があれば、ここでもメッセージは表示されないはずです。
5. NVDAメニューの[ツール(T)]→[ログビューアー(L)]を開き、ログの内容を確認する。

2023-12-30 06:33 UTC, kitabatake1013 commented
以下、備忘目的でメモしておきます。

Issueの作成に成功したとき、現状は何もメッセージを表示しません。
これは、特にユーザからの操作を必要としないタイミングでモーダルダイアログを表示することで、スレッドの動作がブロックされてしまうのは好ましくないだろうという考えからです。
ただ、英語カナ変換や自動更新チェックのの有効化・無効化では結果を表示しているので、そちらに合わせて「完了」のようなメッセージを出すことを検討しています。

また、[第三者がこの機能で作成したIssue](https://github.com/kitabatake1013/gh_issue_test/issues/10)を確認すると、ラベルが期待通りに付与されていないことがわかりました。
そこで、Issueのタイトルが「読み方変更リクエスト：」で始まるものはこのアドオンで報告されたものだと見なす、などの方法を採用できないか調査します。

2023-12-30 07:01 UTC, yamahubuki commented
401エラーは、トークンを御入力した際のものでした。
ログがエラーレベルになっていたのもあって、拾えてないものと思ってしまいました。失礼しました。

残る課題は上記コメントの内容のもののみと思いますので、それらが解決されたらApproveします。

2023-12-30 07:01 UTC, kitabatake1013 commented
APIへのリクエスト時にエラーレスポンスが返ってきても、例外が発生しないようにすることも検討します。
ただし、上記よりも優先順位は低くなります。

2023-12-30 08:54 UTC, kitabatake1013 commented
上記、すべて修正しました。

2023-12-30 14:39 UTC, yamahubuki approved these changes

2023-12-30 14:55 UTC, merged